services:
  db:
    image: postgres:17-alpine
    container_name: postgreSQL
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ricardocuellar
      POSTGRES_PASSWORD: 5696
      POSTGRES_DB: blogfastapi
