[project]
name = "first-steps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "JesusPereira-ctrl", email = "jesuspereirap100@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "psycopg[binary]>=3.3.5",
    "sqlalchemy>=2.0",
]
[tool.fastapi]
entrypoint = "src.main:app"
